object LibVersions {

    const val gradleVersion = "3.5.3"
    const val kotlinVersion = "1.3.61"
    const val appcompatVersion = "1.1.0"
    const val cardLayoutVersion = "1.0.0"
    const val junitVersion = "4.12"
    const val daggerVersion = "2.24"
    const val retrofitVersion = "2.6.2"
    const val okhttpVersion = "4.2.2"
    const val gsonVersion = "2.8.6"
    const val multidexVersion = "2.0.1"
    const val lifecycleVersion = "1.1.1"
    const val constraintLayoutVersion = "1.1.3"
    const val viewModelKtxVersion = "2.2.0-rc03"
    const val picassoVersion = "2.71828"
    const val coroutinesTestVersion = "1.3.2"
    const val mockitoVersion = "2.2.0"
    const val coreTestingArch = "2.1.0"
    const val pagingLibVersion = "2.1.1"
}